### PR TITLE
Fixvalueasstringerror

### PR DESCRIPTION
**Pull request by vladbelozertsev**
Hi, i found a better solution for types, please check it.
Changes:
1) We don’t need to add numbered styles by hands. String type (‘@ms ’, ‘@vs’, etc) automatically add to all numbered styles. It means StringifiedStyles is unnecessary for now.
2) I add TS regex types for sizes, based on documentation. For example in current version we can write without error something like - {fontSize: ‘any-symbols’}. In this PR regex types solve the problem. I check, regex types work since last RN version (0.72.4), because of style types was updated - removed ‘string’ type from styles that consume a number value. This is actually why RNSM types have broken
Thanks

### CODE REVIEW

**Comment by nirsky** [comment]
Hey @vladbelozertsev! Looks good but there some conflicts with your previous commit. Can you please resolve them?

**Comment by vladbelozertsev** [comment]
@nirsky done.

**Comment by vladbelozertsev** [comment]
Is it ok? Or mb better to create a new fork?

**Comment by endyinthesun** [comment]
@vladbelozertsev hi! Could you create a new PR and add "rowGap", "columnGap" and "gap"?

**Review by nirsky — APPROVED** [review]

**Comment by vladbelozertsev** [comment]
@endyinthesun hi, is it your specific values? They are not includes to [documentation](https://www.npmjs.com/package/react-native-size-matters#scaledsheet)

**Comment by vladbelozertsev** [comment]
@endyinthesun oh sry, its basic css styles, they are included to current PR

**Pull request merged**
