### PR TITLE
Added moderateVerticalScale

### PR DESCRIPTION
**Pull request by SrBrahma**
#45 

Made this thinking of a title text. I want my title to be 0.2y if my screen is 1x1y or 2x1y. Also, ain't concerned if it is going to fit horizontally or not.

### CODE REVIEW

**Review by nirsky — CHANGES_REQUESTED** [review]
Thanks for the PR.
Please add tests - it is important to keep high test coverage.

**Comment by SrBrahma** [comment]
Thanks for "forcing" me to write the tests. Never did it but practically showed me the benefits of it and also its need of doing so.

Also, can you please answer #44? Still ain't sure about the factor. I am using 0.3 in everything as the examples use in fontSize and is looking good in my 6" device and a emulated 2.7" one (still have to test in a tablet), but still a magic number for me.

**Comment by nirsky** [comment]
Thanks for the tests!
Not sure why, but you messed something in the README :/



Notice the spaces and the new lines, it changed.
Please make sure to revert the changes on the untouched lines, and keep the alignment for the additions you made.

The same goes for the `Motivation` section, there are some unneeded changes there (probably your IDE made them using auto-formatting).

**Comment by SrBrahma** [comment]
I have added the new lines at the functions because the MD preview was showing them at the same line / in a weird way, but, looks like GitHub displays the MD with some differences regarding this. Looks I reverted it. If you see any other problem, feel free to change it.

**Pull request merged**
